apiVersion: apps/v1
kind: Deployment
metadata:
  name: Book-My-Show-app
  labels:
    app: Book-My-Show
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Book-My-Show
  template:
    metadata:
      labels:
        app: Book-My-Show
    spec:
      containers:
      - name: Book-My-Show-container
        image: pankaj0791/book-my-show:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000  # Replace with the port your app runs on
